// Code generated by testgen. DO NOT EDIT.
package registration

import (
	"testing"
	"time"
)

// TestValidateRegisterRequest сгенерирован testgen.
// TODO: дополни проверки got* в соответствии с бизнес-логикой
// (см. строки '_ = gotN' ниже — там стоят TODO-комментарии).
func TestValidateRegisterRequest(t *testing.T) {
	tests := []struct {
		name     string
		inputReq RegisterRequest
		wantErr  bool
	}{
		{
			name:     "ValidateRegisterRequest/success",
			inputReq: RegisterRequest{Email: "user@example.com", Name: "Test User", Age: 25, Phone: "+79991234567", Address: Address{City: "Moscow", Street: "Tverskaya", House: "1"}, CreatedAt: time.Now()},
			wantErr:  false,
		},
		{
			name:     "ValidateRegisterRequest/error_empty_email",
			inputReq: RegisterRequest{Email: "", Name: "Test User", Age: 25, Phone: "+79991234567", Address: Address{City: "Moscow", Street: "Tverskaya", House: "1"}, CreatedAt: time.Now()},
			wantErr:  true,
		},
		{
			name:     "ValidateRegisterRequest/error_invalid_email",
			inputReq: RegisterRequest{Email: "invalid-email", Name: "Test User", Age: 25, Phone: "+79991234567", Address: Address{City: "Moscow", Street: "Tverskaya", House: "1"}, CreatedAt: time.Now()},
			wantErr:  true,
		},
		{
			name:     "ValidateRegisterRequest/error_empty_name",
			inputReq: RegisterRequest{Email: "user@example.com", Name: "", Age: 25, Phone: "+79991234567", Address: Address{City: "Moscow", Street: "Tverskaya", House: "1"}, CreatedAt: time.Now()},
			wantErr:  true,
		},
		{
			name:     "ValidateRegisterRequest/error_underage",
			inputReq: RegisterRequest{Email: "user@example.com", Name: "Test User", Age: 17, Phone: "+79991234567", Address: Address{City: "Moscow", Street: "Tverskaya", House: "1"}, CreatedAt: time.Now()},
			wantErr:  true,
		},
		{
			name:     "ValidateRegisterRequest/error_empty_city",
			inputReq: RegisterRequest{Email: "user@example.com", Name: "Test User", Age: 25, Phone: "+79991234567", Address: Address{City: "", Street: "Tverskaya", House: "1"}, CreatedAt: time.Now()},
			wantErr:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := ValidateRegisterRequest(tt.inputReq)
			if (err != nil) != tt.wantErr {
				t.Errorf("got err = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
		})
	}
}
