// Code generated by testgen. DO NOT EDIT.
package registration

import (
	"testing"
)

// TestValidateRegisterRequest сгенерирован testgen.
// TODO: дополни проверки got* в соответствии с бизнес-логикой
// (см. строки '_ = gotN' ниже — там стоят TODO-комментарии).
func TestValidateRegisterRequest(t *testing.T) {
	tests := []struct {
		name     string
		inputReq RegisterRequest
		wantErr  bool
	}{
		{
			name:     "ValidateRegisterRequest/success",
			inputReq: RegisterRequest{},
			wantErr:  false,
		},
		{
			name:     "ValidateRegisterRequest/error",
			inputReq: RegisterRequest{},
			wantErr:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := ValidateRegisterRequest(tt.inputReq)
			if (err != nil) != tt.wantErr {
				t.Errorf("got err = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
		})
	}
}
