package app_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yourorg/testgen/internal/app"
)

// ── resolveOutputPath ─────────────────────────────────────────────────────────

func TestResolveOutputPath_explicitOutputFile(t *testing.T) {
	cfg := app.Config{
		Target:     "./example/service",
		OutputFile: "/tmp/my_test.go",
	}
	got := app.ResolveOutputPath(cfg, "service")
	if got != "/tmp/my_test.go" {
		t.Errorf("explicit -o: got %q, want /tmp/my_test.go", got)
	}
}

func TestResolveOutputPath_singleGoFile(t *testing.T) {
	dir := t.TempDir()

	sourceFile := filepath.Join(dir, "service.go")
	if err := os.WriteFile(sourceFile, []byte("package service\n"), 0o644); err != nil {
		t.Fatalf("write source file: %v", err)
	}

	cfg := app.Config{Target: sourceFile}

	got := app.ResolveOutputPath(cfg, "service")
	want := filepath.Join(dir, "service_test.go")

	if filepath.Clean(got) != filepath.Clean(want) {
		t.Errorf("single file: got %q, want %q", got, want)
	}
}

func TestResolveOutputPath_dirWithOneProductionFile(t *testing.T) {
	// Директория с ровно одним production .go файлом.
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "service.go"), "package service\n")

	cfg := app.Config{Target: dir}
	got := app.ResolveOutputPath(cfg, "service")
	want := filepath.Join(dir, "service_test.go")
	if got != want {
		t.Errorf("dir one file: got %q, want %q", got, want)
	}
}

func TestResolveOutputPath_dirWithOneFile_ignoresTestFile(t *testing.T) {
	// Директория: один production файл + существующий *_test.go не считается.
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "registration.go"), "package registration\n")
	writeFile(t, filepath.Join(dir, "registration_test.go"), "package registration\n")

	cfg := app.Config{Target: dir}
	got := app.ResolveOutputPath(cfg, "registration")
	want := filepath.Join(dir, "registration_test.go")
	if got != want {
		t.Errorf("ignores test file: got %q, want %q", got, want)
	}
}

func TestResolveOutputPath_dirWithMultipleFiles_usesPkgName(t *testing.T) {
	// Директория: несколько production файлов → <pkgName>_test.go
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "handler.go"), "package api\n")
	writeFile(t, filepath.Join(dir, "router.go"), "package api\n")

	cfg := app.Config{Target: dir}
	got := app.ResolveOutputPath(cfg, "api")
	want := filepath.Join(dir, "api_test.go")
	if got != want {
		t.Errorf("multi files: got %q, want %q", got, want)
	}
}

func TestResolveOutputPath_noTestgenInName(t *testing.T) {
	// Результат никогда не должен содержать "testgen_generated".
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "calculator.go"), "package calculator\n")

	cfg := app.Config{Target: dir}
	got := app.ResolveOutputPath(cfg, "calculator")
	if strings.Contains(got, "testgen_generated") {
		t.Errorf("output path содержит testgen_generated: %q", got)
	}
	if !strings.HasSuffix(got, "calculator_test.go") {
		t.Errorf("ожидался calculator_test.go, got %q", got)
	}
}

// ── checkOverwrite ────────────────────────────────────────────────────────────

func TestCheckOverwrite_fileNotExist(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nonexistent_test.go")
	if err := app.CheckOverwrite(path); err != nil {
		t.Errorf("несуществующий файл: ожидался nil, got %v", err)
	}
}

func TestCheckOverwrite_generatedFile_canOverwrite(t *testing.T) {
	path := filepath.Join(t.TempDir(), "gen_test.go")
	content := "// Code generated by testgen. DO NOT EDIT.\npackage pkg\n"
	writeFile(t, path, content)

	if err := app.CheckOverwrite(path); err != nil {
		t.Errorf("сгенерированный файл: ожидался nil, got %v", err)
	}
}

func TestCheckOverwrite_manualFile_returnsError(t *testing.T) {
	path := filepath.Join(t.TempDir(), "manual_test.go")
	content := "package pkg\n\nfunc TestFoo(t *testing.T) {}\n"
	writeFile(t, path, content)

	err := app.CheckOverwrite(path)
	if err == nil {
		t.Fatal("ручной файл: ожидалась ошибка, got nil")
	}
	if !strings.Contains(err.Error(), "not generated by testgen") {
		t.Errorf("неожиданный текст ошибки: %v", err)
	}
}

func TestCheckOverwrite_emptyFile_returnsError(t *testing.T) {
	path := filepath.Join(t.TempDir(), "empty_test.go")
	writeFile(t, path, "")

	err := app.CheckOverwrite(path)
	if err == nil {
		t.Fatal("пустой файл: ожидалась ошибка, got nil")
	}
}

// writeFile — вспомогательная функция создания файла в тестах.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("writeFile %s: %v", path, err)
	}
}
