package app

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ResolveOutputPath — экспортированная обёртка для тестирования.
var ResolveOutputPath = resolveOutputPath

// CheckOverwrite — экспортированная обёртка для тестирования.
var CheckOverwrite = checkOverwrite

// По ней определяем, безопасно ли перезаписать существующий файл.
const generatedHeader = "// Code generated by testgen. DO NOT EDIT."

// resolveOutputPath возвращает абсолютный путь выходного файла.
//
// Приоритеты:
//  1. cfg.OutputFile задан явно → использовать как есть.
//  2. Target — конкретный .go файл:
//     ./example/service/service.go → ./example/service/service_test.go
//  3. Target — директория:
//     * ровно один production Go-файл → <basename>_test.go
//     example/service/service.go → service_test.go
//     * несколько production файлов  → <pkgName>_test.go
//     package registration         → registration_test.go
//
// Production файлы = *.go без *_test.go суффикса.
func resolveOutputPath(cfg Config, pkgName string) string {
	// 1. Явный путь.
	if cfg.OutputFile != "" {
		return cfg.OutputFile
	}

	info, err := os.Stat(cfg.Target)

	// 2. Одиночный .go файл.
	if err == nil && !info.IsDir() && strings.HasSuffix(cfg.Target, ".go") {
		dir := filepath.Dir(cfg.Target)
		base := filepath.Base(cfg.Target)
		name := strings.TrimSuffix(base, filepath.Ext(base)) + "_test.go"

		if dir == "." {
			return name
		}

		return filepath.Join(dir, name)
	}

	// 3. Директория.
	dir := cfg.Target
	if err != nil {
		dir = "."
	}

	entries, readErr := os.ReadDir(dir)
	if readErr == nil {
		var prodFiles []string
		for _, e := range entries {
			if e.IsDir() {
				continue
			}

			name := e.Name()
			if strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") {
				prodFiles = append(prodFiles, name)
			}
		}

		if len(prodFiles) == 1 {
			base := strings.TrimSuffix(prodFiles[0], ".go")
			return filepath.Join(dir, base+"_test.go")
		}
	}

	// 4. Несколько файлов или не удалось прочитать директорию → <pkgName>_test.go.
	if pkgName == "" {
		pkgName = "pkg"
	}

	return filepath.Join(dir, pkgName+"_test.go")
}

// checkOverwrite проверяет, разрешено ли записать в path.
//
// Правила:
//   - файл не существует → OK.
//   - файл существует и начинается с generatedHeader → OK (наш файл).
//   - файл существует и НЕ начинается с generatedHeader → ошибка:
//     пользователь создал тест вручную; перезапись опасна.
func checkOverwrite(path string) error {
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return nil // файл не существует — всё ОК
	}
	if err != nil {
		return fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	// Читаем ровно столько байт, сколько нужно для проверки заголовка.
	buf := make([]byte, len(generatedHeader))
	n, _ := f.Read(buf)
	if bytes.HasPrefix(buf[:n], []byte(generatedHeader)) {
		return nil // наш сгенерированный файл — перезаписываем
	}

	return fmt.Errorf(
		"output file %q already exists and is not generated by testgen; "+
			"specify -o to override manually",
		path,
	)
}
