// Code generated by testgen. DO NOT EDIT.
package service_test

import (
	"context"
	"github.com/gojuno/minimock/v3"
	service "github.com/yourorg/testgen/example/service"
	mock "github.com/yourorg/testgen/example/service/mock"
	"testing"
)

// testMocks объединяет все мок-объекты, используемые в тестах файла.
// Каждое поле инициализируется через minimock.NewController в t.Run.
type testMocks struct {
	repo *mock.UserRepositoryMock
}

// TestNewService сгенерирован testgen.
// TODO: дополни проверки got* в соответствии с бизнес-логикой
// (см. строки '_ = gotN' ниже — там стоят TODO-комментарии).
func TestNewService(t *testing.T) {
	tests := []struct {
		name      string
		inputRepo service.UserRepository
	}{
		{
			name:      "NewService/success",
			inputRepo: nil, // TODO: подставь mock/stub для UserRepository
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got0 := service.NewService(tt.inputRepo)
			_ = got0 // TODO: verify got0 with business-specific expected value
		})
	}
}

// TestService_GetUserName сгенерирован testgen.
// TODO: дополни проверки got* в соответствии с бизнес-логикой
// (см. строки '_ = gotN' ниже — там стоят TODO-комментарии).
// Для каждой строки таблицы реализуй prepare(m *testMocks):
// настрой ожидания минимок-моков, например m.<fieldName>.<Method>Mock.Expect(...).Return(...).
func TestService_GetUserName(t *testing.T) {
	// TODO: удали t.Skip после того как настроишь minimock expectations в prepare(m *testMocks).
	t.Skip("testgen scaffold: configure minimock expectations before enabling this test")
	tests := []struct {
		name     string
		inputCtx context.Context
		inputId  int64
		wantErr  bool
		prepare  func(m *testMocks)
	}{
		{
			name:     "GetUserName/success",
			inputCtx: context.Background(),
			inputId:  42,
			wantErr:  false,
			prepare: func(m *testMocks) {
				// TODO: configure minimock expectations for this scenario
			},
		},
		{
			name:     "GetUserName/error",
			inputCtx: nil,
			inputId:  0,
			wantErr:  true,
			prepare: func(m *testMocks) {
				// TODO: configure minimock expectations for this scenario
			},
		},
		{
			name:     "GetUserName/edge_nil_ctx",
			inputCtx: nil,
			inputId:  42,
			wantErr:  true,
			prepare: func(m *testMocks) {
				// TODO: configure minimock expectations for this scenario
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mc := minimock.NewController(t)
			m := &testMocks{
				repo: mock.NewUserRepositoryMock(mc),
			}
			if tt.prepare != nil {
				tt.prepare(m)
			}
			rcv := service.NewService(m.repo)
			got0, err := rcv.GetUserName(tt.inputCtx, tt.inputId)
			if (err != nil) != tt.wantErr {
				t.Errorf("got err = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
			_ = got0 // TODO: verify got0 with business-specific expected value
		})
	}
}
