// Code generated by testgen. DO NOT EDIT.
package advanced

import (
	"context"
	"io"
	"strings"
	"testing"
)

// TestProcess сгенерирован testgen.
// TODO: дополни проверки got* в соответствии с бизнес-логикой
// (см. строки '_ = gotN' ниже — там стоят TODO-комментарии).
func TestProcess(t *testing.T) {
	tests := []struct {
		name       string
		inputCtx   context.Context
		inputR     io.Reader
		inputP     *int
		inputItems []string
		wantErr    bool
	}{
		{
			name:       "Process/success",
			inputCtx:   context.Background(),
			inputR:     strings.NewReader("test-value"),
			inputP:     new(int),
			inputItems: []string{"test-value"},
			wantErr:    false,
		},
		{
			name:       "Process/error",
			inputCtx:   nil,
			inputR:     nil,
			inputP:     nil,
			inputItems: nil,
			wantErr:    true,
		},
		{
			name:       "Process/edge_nil_ctx",
			inputCtx:   nil,
			inputR:     strings.NewReader("test-value"),
			inputP:     new(int),
			inputItems: []string{"test-value"},
			wantErr:    true,
		},
		{
			name:       "Process/edge_nil_r",
			inputCtx:   context.Background(),
			inputR:     nil,
			inputP:     new(int),
			inputItems: []string{"test-value"},
			wantErr:    true,
		},
		{
			name:       "Process/edge_nil_p",
			inputCtx:   context.Background(),
			inputR:     strings.NewReader("test-value"),
			inputP:     nil,
			inputItems: []string{"test-value"},
			wantErr:    true,
		},
		{
			name:       "Process/edge_empty_items",
			inputCtx:   context.Background(),
			inputR:     strings.NewReader("test-value"),
			inputP:     new(int),
			inputItems: []string{},
			wantErr:    true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := Process(tt.inputCtx, tt.inputR, tt.inputP, tt.inputItems)
			if (err != nil) != tt.wantErr {
				t.Errorf("got err = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
		})
	}
}

// TestValidate сгенерирован testgen.
// TODO: дополни проверки got* в соответствии с бизнес-логикой
// (см. строки '_ = gotN' ниже — там стоят TODO-комментарии).
func TestValidate(t *testing.T) {
	tests := []struct {
		name    string
		inputS  string
		wantErr bool
	}{
		{
			name:    "Validate/success",
			inputS:  "test-value",
			wantErr: false,
		},
		{
			name:    "Validate/error",
			inputS:  "",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := Validate(tt.inputS)
			if (err != nil) != tt.wantErr {
				t.Errorf("got err = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
		})
	}
}
